main:
  - name: About
    url: '#about'
    weight: 1
  - name: Research
    url: /research/
    weight: 2
  - name: News
    url: '#-news'
    weight: 3
  - name: CV
    url: /cv/CV_Pan.pdf
    weight: 4